# Generated by Django 5.1.1 on 2024-10-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_cards', to='accounts.account'),
        ),
    ]
